apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/bgd
patches:
  - path: deployment-patch.yaml
  - target:
      kind: Service
      name: bgd-service
      version: v1
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 8080
  
namespace: sandbox
