apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bgd-deployment
spec:
  selector:
    matchLabels:
      app: bgd
  replicas: 3
  template:
    metadata:
      labels:
        app:  bgd
    spec:
      containers:
      - name:  bgd
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 200m
            memory: 1Gi
        env:
        - name: COLOR
          value: "yellow"