apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bgd-deployment
  labels:
    app:  bgd
spec:
  selector:
    matchLabels:
      app: bgd
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  bgd
    spec:
      containers:
      - name:  bgd
        image:  quay.io/rhdevelopers/bgd:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  bgd-port